# Generated by Django 3.1.dev20200417182300 on 2020-12-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(null=True, upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('shorttitle', models.CharField(max_length=50)),
                ('copyright', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
