# Generated by Django 3.1.dev20200417182300 on 2020-12-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20201219_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('keyword', models.TextField()),
                ('description', models.TextField()),
                ('logo', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Metadatas',
                'verbose_name_plural': 'Metadata',
            },
        ),
    ]
