# Generated by Django 3.1.dev20200417182300 on 2020-12-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_metadatas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('shorttitle', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('postedby', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Works',
                'verbose_name_plural': 'Work',
            },
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Footers', 'verbose_name_plural': 'Footer'},
        ),
    ]
