# Generated by Django 3.1.dev20200417182300 on 2020-12-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20201220_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('shorttitle', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('postedby', models.CharField(max_length=50)),
                ('postdate', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Blogs',
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='Whoweare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('shorttitle', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Whoweares',
                'verbose_name_plural': 'Whoweare',
            },
        ),
    ]
