# Generated by Django 3.0.7 on 2020-12-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_blog_whoweare'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('shorttitle', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('shortimage', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Blogs',
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
