# Generated by Django 3.0.7 on 2020-12-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Abouts', 'verbose_name_plural': 'About'},
        ),
    ]
