# Generated by Django 3.0.7 on 2020-12-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20201221_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='postdate',
            field=models.DateField(),
        ),
    ]
