# Generated by Django 3.0.7 on 2020-12-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20201221_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='postdate',
            field=models.CharField(max_length=50),
        ),
    ]
